- hosts: all
  tasks:
  - name: "Install httpd"
    package:
          name: httpd
          state: present
  - name: "copy the content"
    copy:
          src: "/root/web.html"
          dest: "/var/www/html"

  - name: "restart the httpd service"
    service:
          name: httpd
          state: restarted
